version: '3'

services:
  test_task74:
    user: "${UID}:${GID}"
    image: php:7.4-apache
    command: bash -c "source /etc/apache2/envvars; a2enmod rewrite; composer install --working-dir /var/www/composer; composer cc; rmdir /var/www/composer/cache; rm /var/www/composer/.htaccess; service apache2 stop; usermod -u ${UID} www-data; chown -R www-data:www-data /var/www/*; apache2 -D FOREGROUND"
    ports:
      - 80:80
    volumes:
      - ./composer:/var/www/composer
      - ./app:/var/www/html
      - ./backend:/var/www/backend
      - ./database:/var/www/database
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      COMPOSER_HOME: /var/www/composer