version: '3'

services:
  web:
    user: "${UID}:${GID}"
    image: php:7.4-apache
    ports:
      - 80:80
    volumes:
      - ./app:/var/www/html
      - ./vendor:/var/www/vendor
      - ./backend:/var/www/backend
      - ./database:/var/www/database
